# console, file
# file - rewrite each time
version: 1
log_root: '|'
formatters:
  cons:
    format: '%(name)s,  %(levelname)s - %(message)s'
  file:
#    format: '%(asctime)s :  %(name)s - %(levelname)s - %(message)s'
    format: '%(asctime)s :  %(name)s - %(levelname)s - %(message)s IN %(module)% '
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: cons
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: file
    filename: 'test.log'
    # re-write file every time
    mode: 'w'
    # append to log file every time
    # mode: 'a'
loggers:
  '|':
    level: DEBUG
    handlers: [console,file]
    propagate: no
root:
  level: DEBUG
  #handlers: [console,file]
